# Autogenerated wrapper script for LanceDB_C_jll for x86_64-w64-mingw32
export lancedb_h, liblancedb

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("LanceDB_C")
JLLWrappers.@declare_file_product(lancedb_h)
JLLWrappers.@declare_library_product(liblancedb, "lancedb.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_file_product(
        lancedb_h,
        "include\\lancedb.h",
    )

    JLLWrappers.@init_library_product(
        liblancedb,
        "bin\\lancedb.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
