# Autogenerated wrapper script for LanceDB_C_jll for x86_64-apple-darwin
export lancedb_h, liblancedb

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("LanceDB_C")
JLLWrappers.@declare_file_product(lancedb_h)
JLLWrappers.@declare_library_product(liblancedb, "@rpath/liblancedb.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_file_product(
        lancedb_h,
        "include/lancedb.h",
    )

    JLLWrappers.@init_library_product(
        liblancedb,
        "lib/liblancedb.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
